import type { TrendSeed } from './trend-types';

const detectedAt = '2026-05-20T09:48:00.000Z';
const lastUpdatedAt = '2026-05-20T11:48:00.000Z';

export const trendSeeds: TrendSeed[] = [
  {
    id: 'avant-apres-brutal',
    name: 'Avant / Après brutal',
    category: 'visual_format',
    platform: 'tiktok',
    detectedAt,
    lastUpdatedAt,
    volumeScore: 58,
    velocityScore: 86,
    accelerationScore: 82,
    saturationScore: 32,
    noveltyScore: 78,
    creatorFitScore: 88,
    difficultyScore: 42,
    riskScore: 28,
    recommendedNiches: ['Business', 'Coaching', 'Fitness', 'Beauté', 'Lifestyle'],
    badFitNiches: ['Gaming'],
    timeWindow: { label: 'Fenêtre courte : 36-48h', estimatedHoursLeft: 42 },
    signals: [
      { label: 'Croissance formats similaires', value: '+38%', sentiment: 'positive', explanation: 'Les contenus avec contraste visuel progressent dans plusieurs niches.' },
      { label: 'Saturation business', value: 'faible', sentiment: 'positive', explanation: 'Le format reste peu copié dans les niches expertise et offre.' },
      { label: 'Commentaires curiosité', value: 'en hausse', sentiment: 'positive', explanation: 'Les viewers demandent la méthode après avoir vu l’écart.' },
    ],
    explanation: 'Le contraste rend la promesse visible avant même que le créateur explique.',
    whyItWorks: 'Le viewer compare deux états et reste pour comprendre ce qui a créé l’écart.',
    whyNow: 'Le format monte parce que les créateurs remplacent les intros longues par une preuve visuelle immédiate.',
    saturationReason: 'Encore early car la plupart des versions restent centrées sur la beauté ou le fitness, pas sur le business.',
    recommendedFormats: [
      { label: 'Carrousel 5 slides', duration: '5 slides', difficulty: 'easy', why: 'Le contraste est lisible et sauvegardable.' },
      { label: 'Facecam + preuve écran', duration: '18-25 sec', difficulty: 'medium', why: 'La preuve arrive à 0:00 puis l’explication garde la tension.' },
    ],
    hooks: [
      'J’ai arrêté de faire ça, et mes vidéos ont enfin commencé à retenir les gens.',
      'Avant je faisais cette erreur. Après, mes vidéos sont devenues beaucoup plus tendues.',
      'Le changement paraît petit, mais il transforme toute la vidéo.',
    ],
    angles: [
      'Montre une erreur que ton audience fait encore, puis révèle la version corrigée.',
      'Compare une intro lente avec une intro qui annonce directement l’enjeu.',
      'Affiche le résultat final, puis remonte vers la décision qui l’a créé.',
    ],
    mistakesToAvoid: ['Avant trop vague', 'Après sans preuve', 'Intro explicative', 'Promesse plus forte que le résultat'],
    actionPlan: [
      { title: 'Choisir une preuve visuelle', description: 'Trouve un avant/après que l’on comprend sans contexte.', effort: 'low', priority: 'high' },
      { title: 'Écrire le hook en conséquence', description: 'Annonce la perte ou le résultat avant la méthode.', effort: 'low', priority: 'high' },
      { title: 'Couper toute intro', description: 'Le premier plan doit déjà montrer le contraste.', effort: 'medium', priority: 'medium' },
    ],
  },
  {
    id: 'test-7-jours',
    name: 'J’ai testé pendant 7 jours',
    category: 'storytelling',
    platform: 'tiktok',
    detectedAt,
    lastUpdatedAt,
    volumeScore: 71,
    velocityScore: 79,
    accelerationScore: 74,
    saturationScore: 51,
    noveltyScore: 62,
    creatorFitScore: 81,
    difficultyScore: 55,
    riskScore: 42,
    recommendedNiches: ['Fitness', 'Business', 'Food', 'Lifestyle', 'Éducation'],
    badFitNiches: ['Beauté'],
    timeWindow: { label: 'Fenêtre : 48-72h', estimatedHoursLeft: 64 },
    signals: [
      { label: 'Formats journal de bord', value: '+24%', sentiment: 'positive', explanation: 'Les séries courtes regagnent du momentum.' },
      { label: 'Promesse temporelle', value: 'stable', sentiment: 'neutral', explanation: 'Le format reste compris rapidement.' },
      { label: 'Risque répétition', value: 'moyen', sentiment: 'neutral', explanation: 'Les versions sans résultat réel commencent à fatiguer.' },
    ],
    explanation: 'La contrainte de 7 jours donne une preuve temporelle et une fin claire.',
    whyItWorks: 'Le viewer veut savoir si l’expérience tient jusqu’au résultat final.',
    whyNow: 'Les créateurs cherchent des formats plus crédibles que le conseil direct.',
    saturationReason: 'La structure est connue, mais les niches business et éducation restent exploitables avec une vraie mesure.',
    recommendedFormats: [
      { label: 'Journal de bord rapide', duration: '24-32 sec', difficulty: 'medium', why: 'Les jours clés créent une progression naturelle.' },
      { label: 'Carrousel résultat', duration: '6 slides', difficulty: 'easy', why: 'Le test devient une checklist sauvegardable.' },
    ],
    hooks: [
      'J’ai testé cette méthode pendant 7 jours, voilà ce qui a vraiment changé.',
      'Je pensais que ça ne ferait rien. Au jour 4, j’ai compris le problème.',
      '7 jours, une seule règle, et un résultat que je n’attendais pas.',
    ],
    angles: ['Tester une routine de publication plus courte.', 'Documenter une correction de hook sur plusieurs posts.', 'Comparer une méthode populaire avec ton résultat réel.'],
    mistakesToAvoid: ['Journal trop lent', 'Pas de mesure claire', 'Conclusion molle', 'Jour 1 trop long'],
    actionPlan: [
      { title: 'Définir une règle unique', description: 'Un seul test, une seule mesure, une seule conclusion.', effort: 'low', priority: 'high' },
      { title: 'Montrer le résultat d’abord', description: 'Ouvre avec ce qui a changé, pas avec le contexte.', effort: 'medium', priority: 'high' },
      { title: 'Garder trois jours clés', description: 'Jour 1, jour 4, jour 7 suffisent souvent.', effort: 'medium', priority: 'medium' },
    ],
  },
  {
    id: 'erreur-bloque-vues',
    name: 'L’erreur qui bloque tes vues',
    category: 'hook_format',
    platform: 'tiktok',
    detectedAt,
    lastUpdatedAt,
    volumeScore: 63,
    velocityScore: 84,
    accelerationScore: 80,
    saturationScore: 44,
    noveltyScore: 68,
    creatorFitScore: 92,
    difficultyScore: 28,
    riskScore: 34,
    recommendedNiches: ['Business', 'Coaching', 'Éducation', 'Creator growth'],
    badFitNiches: ['Food'],
    timeWindow: { label: 'Fenêtre courte : 24-48h', estimatedHoursLeft: 34 },
    signals: [
      { label: 'Hooks diagnostic', value: '+41%', sentiment: 'positive', explanation: 'Les formats qui nomment une erreur précise montent vite.' },
      { label: 'Curiosité commentaire', value: 'forte', sentiment: 'positive', explanation: 'Les viewers veulent savoir s’ils sont concernés.' },
      { label: 'Saturation motivation', value: 'haute', sentiment: 'negative', explanation: 'À éviter si le message reste trop général.' },
    ],
    explanation: 'Le hook crée une tension immédiate : le viewer veut vérifier s’il fait l’erreur.',
    whyItWorks: 'La peur d’être concerné ralentit le swipe et force l’attention sur le diagnostic.',
    whyNow: 'Les créateurs veulent des audits courts, pas des conseils génériques.',
    saturationReason: 'Le format devient saturé dans la motivation, mais reste fort quand l’erreur est concrète.',
    recommendedFormats: [
      { label: 'Facecam + exemple écran', duration: '20-28 sec', difficulty: 'easy', why: 'Le diagnostic gagne en crédibilité avec un exemple.' },
      { label: 'Mini audit vertical', duration: '22 sec', difficulty: 'medium', why: 'La correction devient visible immédiatement.' },
    ],
    hooks: [
      'Si tes vidéos bloquent à 300 vues, regarde ça.',
      'Tu penses que ton contenu est nul, mais le vrai problème est ailleurs.',
      'La plupart des créateurs ratent cette partie dans les 2 premières secondes.',
    ],
    angles: ['Montrer une erreur de hook.', 'Comparer une mauvaise intro avec une bonne intro.', 'Faire un mini audit d’une vidéo fictive.'],
    mistakesToAvoid: ['Hook trop vague', 'Promesse trop large', 'Vidéo trop longue', 'Pas de payoff clair'],
    actionPlan: [
      { title: 'Nommer l’erreur en 7 mots', description: 'Le viewer doit comprendre le danger avant 0:02.', effort: 'low', priority: 'high' },
      { title: 'Montrer une mauvaise intro', description: 'Utilise un exemple fictif pour éviter les explications longues.', effort: 'low', priority: 'high' },
      { title: 'Donner la correction exacte', description: 'Termine par une règle de montage réutilisable.', effort: 'medium', priority: 'medium' },
    ],
  },
  {
    id: 'mini-etude-cas',
    name: 'Mini étude de cas',
    category: 'business',
    platform: 'tiktok',
    detectedAt,
    lastUpdatedAt,
    volumeScore: 55,
    velocityScore: 82,
    accelerationScore: 78,
    saturationScore: 35,
    noveltyScore: 76,
    creatorFitScore: 89,
    difficultyScore: 48,
    riskScore: 26,
    recommendedNiches: ['Business', 'E-commerce', 'Coaching', 'Éducation'],
    badFitNiches: ['Gaming'],
    timeWindow: { label: 'Fenêtre courte : 36h', estimatedHoursLeft: 36 },
    signals: [
      { label: 'Cas courts sauvegardés', value: '+32%', sentiment: 'positive', explanation: 'Les formats preuve + leçon sont plus sauvegardables.' },
      { label: 'Commentaires méthode', value: 'en hausse', sentiment: 'positive', explanation: 'Le viewer demande comment reproduire le résultat.' },
      { label: 'Copie massive', value: 'faible', sentiment: 'positive', explanation: 'Le format demande une vraie observation, donc il est moins copié.' },
    ],
    explanation: 'Une mini étude de cas rend le conseil concret et donne une preuve sans faire long.',
    whyItWorks: 'Le conseil ressemble à une observation terrain, pas à une opinion.',
    whyNow: 'Les audiences se méfient des conseils abstraits et restent sur les preuves courtes.',
    saturationReason: 'Le format reste frais car il exige un exemple précis.',
    recommendedFormats: [
      { label: 'Vidéo texte à l’écran', duration: '22-28 sec', difficulty: 'medium', why: 'La décision et le résultat se lisent vite.' },
      { label: 'Carrousel cas', duration: '5 slides', difficulty: 'easy', why: 'Le cas devient un template réutilisable.' },
    ],
    hooks: [
      'Il a changé une seule phrase dans son offre et ses ventes ont doublé.',
      'Cette vidéo n’a pas percé à cause du sujet. Elle a raté son angle.',
      'Un petit changement a rendu le message beaucoup plus clair.',
    ],
    angles: ['Décomposer une vidéo fictive avant/après.', 'Montrer une phrase d’offre corrigée.', 'Transformer un résultat client en leçon créateur.'],
    mistakesToAvoid: ['Cas trop long', 'Preuve confidentielle', 'Conclusion générique', 'Pas de décision claire'],
    actionPlan: [
      { title: 'Choisir un cas minuscule', description: 'Une phrase, une intro ou une offre suffit.', effort: 'low', priority: 'high' },
      { title: 'Montrer la décision', description: 'Le viewer doit voir ce qui a changé.', effort: 'medium', priority: 'high' },
      { title: 'Finir par une règle', description: 'Transforme le cas en décision applicable.', effort: 'low', priority: 'medium' },
    ],
  },
  {
    id: 'resultat-reel-vs-attente',
    name: 'Résultat réel vs attente',
    category: 'ecommerce',
    platform: 'tiktok',
    detectedAt,
    lastUpdatedAt,
    volumeScore: 67,
    velocityScore: 76,
    accelerationScore: 69,
    saturationScore: 48,
    noveltyScore: 61,
    creatorFitScore: 75,
    difficultyScore: 46,
    riskScore: 36,
    recommendedNiches: ['E-commerce', 'Fitness', 'Beauté', 'Food'],
    badFitNiches: ['Business'],
    timeWindow: { label: 'Fenêtre : 48h', estimatedHoursLeft: 48 },
    signals: [
      { label: 'Split-screen preuve', value: '+29%', sentiment: 'positive', explanation: 'Les comparaisons rendent le résultat compréhensible sans contexte.' },
      { label: 'Authenticité', value: 'forte', sentiment: 'positive', explanation: 'Les viewers répondent mieux aux résultats imparfaits mais réels.' },
      { label: 'Saturation produit', value: 'moyenne', sentiment: 'neutral', explanation: 'Le format doit éviter l’effet démo produit classique.' },
    ],
    explanation: 'L’écart entre promesse attendue et résultat réel crée une tension naturelle.',
    whyItWorks: 'Le viewer veut résoudre l’écart entre ce qu’il imaginait et ce qui arrive.',
    whyNow: 'Les formats trop parfaits perdent en crédibilité, les preuves imparfaites montent.',
    saturationReason: 'Le format est déjà visible en e-commerce, mais les angles honnêtes restent efficaces.',
    recommendedFormats: [
      { label: 'Split-screen produit', duration: '20-30 sec', difficulty: 'medium', why: 'L’attente et le résultat sont comparables instantanément.' },
      { label: 'Montage preuve/commentaire', duration: '18-24 sec', difficulty: 'medium', why: 'Le commentaire explique sans ralentir.' },
    ],
    hooks: [
      'Je pensais obtenir ça. Le vrai résultat est beaucoup plus intéressant.',
      'L’attente était simple. Le résultat m’a montré le vrai problème.',
      'Voici ce qui s’est passé quand j’ai testé sans tricher.',
    ],
    angles: ['Comparer promesse marketing et expérience réelle.', 'Montrer l’écart entre méthode populaire et résultat obtenu.', 'Transformer un échec partiel en apprentissage utile.'],
    mistakesToAvoid: ['Résultat trop faible', 'Pas de contexte', 'Montage lent', 'Trop de texte'],
    actionPlan: [
      { title: 'Créer deux frames comparables', description: 'Même cadrage, résultat différent.', effort: 'medium', priority: 'high' },
      { title: 'Nommer l’écart', description: 'Explique ce que le viewer doit observer.', effort: 'low', priority: 'medium' },
      { title: 'Rendre la leçon utile', description: 'Ne termine pas sur “c’était intéressant”.', effort: 'low', priority: 'medium' },
    ],
  },
  {
    id: 'ranking-brutal',
    name: 'Ranking brutal',
    category: 'entertainment',
    platform: 'tiktok',
    detectedAt,
    lastUpdatedAt,
    volumeScore: 82,
    velocityScore: 63,
    accelerationScore: 54,
    saturationScore: 74,
    noveltyScore: 42,
    creatorFitScore: 69,
    difficultyScore: 26,
    riskScore: 58,
    recommendedNiches: ['Gaming', 'Food', 'Beauté', 'Business'],
    badFitNiches: ['Coaching'],
    timeWindow: { label: 'Fenêtre très courte : 12-24h', estimatedHoursLeft: 22 },
    signals: [
      { label: 'Volume très haut', value: '82/100', sentiment: 'neutral', explanation: 'Le format circule beaucoup, donc la concurrence est visible.' },
      { label: 'Commentaires débat', value: 'forts', sentiment: 'positive', explanation: 'Le ranking génère encore des désaccords utiles.' },
      { label: 'Saturation générique', value: 'haute', sentiment: 'negative', explanation: 'Les rankings sans critère précis fatiguent vite.' },
    ],
    explanation: 'Le classement capte l’attention, mais demande une grille de jugement forte.',
    whyItWorks: 'Le viewer reste pour comparer son opinion au classement.',
    whyNow: 'Le format est au pic : bon pour du débat, risqué pour un conseil générique.',
    saturationReason: 'Trop de créateurs classent sans critère clair.',
    recommendedFormats: [
      { label: 'Tier list verticale', duration: '25-35 sec', difficulty: 'easy', why: 'Le désaccord crée les commentaires.' },
      { label: 'Facecam + cartes', duration: '22-30 sec', difficulty: 'medium', why: 'La grille rend le classement plus crédible.' },
    ],
    hooks: [
      'Je classe ces formats du plus risqué au plus rentable.',
      'Ranking brutal : ce format paraît fort, mais il fatigue vite.',
      'Si tu postes ça en 2026, mets-le au moins dans cette catégorie.',
    ],
    angles: ['Classer les hooks par risque de swipe.', 'Classer les formats selon l’effort de production.', 'Classer les idées selon leur potentiel de repost.'],
    mistakesToAvoid: ['Classement sans critère', 'Trop d’items', 'Aucun verdict', 'Ton gratuit'],
    actionPlan: [
      { title: 'Choisir un critère dur', description: 'Risque, effort ou potentiel. Pas les trois.', effort: 'low', priority: 'high' },
      { title: 'Limiter à cinq items', description: 'La vidéo doit rester lisible.', effort: 'low', priority: 'medium' },
      { title: 'Assumer un verdict', description: 'Le commentaire vient du désaccord clair.', effort: 'low', priority: 'medium' },
    ],
  },
  {
    id: 'framework-3-etapes',
    name: 'Framework en 3 étapes',
    category: 'education',
    platform: 'tiktok',
    detectedAt,
    lastUpdatedAt,
    volumeScore: 76,
    velocityScore: 58,
    accelerationScore: 48,
    saturationScore: 69,
    noveltyScore: 38,
    creatorFitScore: 77,
    difficultyScore: 31,
    riskScore: 55,
    recommendedNiches: ['Éducation', 'Coaching', 'Business'],
    badFitNiches: ['Entertainment'],
    timeWindow: { label: 'Fenêtre courte : 12-24h', estimatedHoursLeft: 20 },
    signals: [
      { label: 'Sauvegardes', value: 'stables', sentiment: 'neutral', explanation: 'Le format reste utile quand il est spécifique.' },
      { label: 'Fatigue titres génériques', value: 'haute', sentiment: 'negative', explanation: 'Les “3 étapes pour réussir” sont ignorés.' },
      { label: 'Demandes templates', value: 'moyennes', sentiment: 'neutral', explanation: 'Les viewers gardent les frameworks concrets.' },
    ],
    explanation: 'Le format reste clair mais doit être plus spécifique que les checklists habituelles.',
    whyItWorks: 'Trois étapes réduisent la charge mentale et rendent l’action mémorisable.',
    whyNow: 'Le format est au pic, il fonctionne encore avec une étape inattendue.',
    saturationReason: 'Les versions génériques sont trop copiées.',
    recommendedFormats: [
      { label: 'Carrousel dense', duration: '5 slides', difficulty: 'easy', why: 'Chaque étape devient sauvegardable.' },
      { label: 'Vidéo tableau', duration: '22-30 sec', difficulty: 'medium', why: 'Le créateur montre la logique en temps réel.' },
    ],
    hooks: [
      'Le framework est simple. La plupart des créateurs sautent l’étape 2.',
      'Si ton contenu part dans tous les sens, commence par ces 3 décisions.',
      'Voici la méthode en 3 étapes que j’aurais dû appliquer plus tôt.',
    ],
    angles: ['Créer un framework anti-erreur.', 'Montrer une étape souvent ignorée.', 'Faire une version “avant de poster”.'],
    mistakesToAvoid: ['Étapes trop évidentes', 'Titre générique', 'Aucun exemple', 'CTA mou'],
    actionPlan: [
      { title: 'Renommer le framework', description: 'Le titre doit contenir un contexte précis.', effort: 'low', priority: 'high' },
      { title: 'Ajouter une étape inattendue', description: 'C’est elle qui évite la saturation.', effort: 'medium', priority: 'high' },
      { title: 'Terminer avec une checklist', description: 'Le viewer doit pouvoir l’appliquer au prochain post.', effort: 'low', priority: 'medium' },
    ],
  },
  {
    id: 'pov-business-generique',
    name: 'POV business générique',
    category: 'business',
    platform: 'tiktok',
    detectedAt,
    lastUpdatedAt,
    volumeScore: 91,
    velocityScore: 32,
    accelerationScore: 26,
    saturationScore: 92,
    noveltyScore: 18,
    creatorFitScore: 41,
    difficultyScore: 20,
    riskScore: 88,
    recommendedNiches: ['Business'],
    badFitNiches: ['Coaching', 'Éducation', 'E-commerce', 'Fitness'],
    timeWindow: { label: 'Fenêtre fermée', estimatedHoursLeft: 8 },
    signals: [
      { label: 'Copies détectées', value: 'massives', sentiment: 'negative', explanation: 'Le format est reconnu dès la première seconde.' },
      { label: 'Velocity', value: 'en baisse', sentiment: 'negative', explanation: 'Le volume reste haut mais ne croît plus.' },
      { label: 'Novelty', value: '18/100', sentiment: 'negative', explanation: 'Le pattern visuel et le wording sont usés.' },
    ],
    explanation: 'Le format est visible partout et donne une impression de copie tardive.',
    whyItWorks: 'Il fonctionnait par identification rapide, mais le viewer reconnaît maintenant le pattern.',
    whyNow: 'Ce n’est plus le bon moment. Le signal sert surtout à comprendre ce qu’il faut éviter.',
    saturationReason: 'Trop de vidéos utilisent le même POV sans preuve, enjeu ou twist.',
    recommendedFormats: [
      { label: 'Mini confession précise', duration: '18-22 sec', difficulty: 'medium', why: 'La confession remplace le POV générique par une tension personnelle.' },
      { label: 'Étude de cas courte', duration: '22 sec', difficulty: 'medium', why: 'La preuve remplace la posture.' },
    ],
    hooks: [
      'Le POV business que tout le monde copie a un vrai problème.',
      'Ce format paraît pro, mais il fait swiper plus vite.',
      'Si tu veux utiliser ce POV, change au moins ça.',
    ],
    angles: ['Transformer le POV en confession précise.', 'Montrer pourquoi le format est saturé.', 'Remplacer la posture par un résultat réel.'],
    mistakesToAvoid: ['Copier le wording', 'Faire une morale générale', 'Pas de preuve', 'Musique trop utilisée'],
    actionPlan: [
      { title: 'Ne pas copier', description: 'Utilise cette tendance comme contre-exemple.', effort: 'low', priority: 'high' },
      { title: 'Trouver un twist précis', description: 'Remplace “POV” par une situation mesurable.', effort: 'medium', priority: 'high' },
      { title: 'Ajouter une preuve', description: 'Sans preuve, le format reste mort.', effort: 'medium', priority: 'medium' },
    ],
  },
  {
    id: 'storytime-transformation',
    name: 'Storytime transformation',
    category: 'storytelling',
    platform: 'tiktok',
    detectedAt,
    lastUpdatedAt,
    volumeScore: 73,
    velocityScore: 61,
    accelerationScore: 58,
    saturationScore: 67,
    noveltyScore: 45,
    creatorFitScore: 74,
    difficultyScore: 62,
    riskScore: 61,
    recommendedNiches: ['Business', 'Coaching', 'Lifestyle'],
    badFitNiches: ['Food'],
    timeWindow: { label: 'Fenêtre à détourner : 24h', estimatedHoursLeft: 24 },
    signals: [
      { label: 'Storytimes longs', value: 'en baisse', sentiment: 'negative', explanation: 'Les intros lentes décrochent trop tôt.' },
      { label: 'Transformation claire', value: 'stable', sentiment: 'positive', explanation: 'La promesse reste forte quand le résultat arrive vite.' },
      { label: 'Risque contexte', value: 'élevé', sentiment: 'negative', explanation: 'Le format meurt si le créateur raconte trop avant l’enjeu.' },
    ],
    explanation: 'Le storytime fonctionne encore si la transformation commence par la conséquence.',
    whyItWorks: 'Une histoire garde l’attention quand elle annonce ce qui a été perdu, gagné ou compris.',
    whyNow: 'Le format est saturé en version longue, mais utile en version diagnostic.',
    saturationReason: 'Les viewers ont vu trop d’intros “il m’est arrivé un truc”.',
    recommendedFormats: [
      { label: 'Facecam tension courte', duration: '25-35 sec', difficulty: 'hard', why: 'La voix porte l’histoire si l’enjeu arrive vite.' },
      { label: 'Storytime en 4 cuts', duration: '24 sec', difficulty: 'medium', why: 'Chaque cut avance une décision.' },
    ],
    hooks: [
      'J’ai perdu du temps avec cette décision, alors que le problème était visible dès le début.',
      'Cette erreur m’a appris une règle simple pour mes vidéos.',
      'Je pensais raconter une histoire. En réalité, je cachais le vrai enjeu.',
    ],
    angles: ['Commencer par la conséquence, pas le contexte.', 'Transformer l’histoire en diagnostic.', 'Raconter uniquement la décision qui change tout.'],
    mistakesToAvoid: ['Intro lente', 'Trop de contexte', 'Aucun enjeu', 'Fin morale générique'],
    actionPlan: [
      { title: 'Ouvrir par la conséquence', description: 'Le viewer doit savoir pourquoi il reste.', effort: 'low', priority: 'high' },
      { title: 'Couper le contexte', description: 'Garde seulement les détails qui expliquent la décision.', effort: 'medium', priority: 'high' },
      { title: 'Finir par une règle', description: 'La transformation doit devenir utile.', effort: 'low', priority: 'medium' },
    ],
  },
  {
    id: 'analyse-flop',
    name: 'Analyse d’un flop',
    category: 'creator_growth',
    platform: 'tiktok',
    detectedAt,
    lastUpdatedAt,
    volumeScore: 49,
    velocityScore: 78,
    accelerationScore: 83,
    saturationScore: 29,
    noveltyScore: 83,
    creatorFitScore: 94,
    difficultyScore: 52,
    riskScore: 24,
    recommendedNiches: ['Creator growth', 'Business', 'Éducation', 'Coaching'],
    badFitNiches: ['Beauté'],
    timeWindow: { label: 'Fenêtre early : 48-72h', estimatedHoursLeft: 58 },
    signals: [
      { label: 'Formats audit', value: '+44%', sentiment: 'positive', explanation: 'Les audiences veulent comprendre les erreurs réelles.' },
      { label: 'Saturation', value: 'basse', sentiment: 'positive', explanation: 'Peu de créateurs assument de montrer un flop.' },
      { label: 'Crédibilité', value: 'forte', sentiment: 'positive', explanation: 'L’analyse d’échec rend le conseil plus fiable.' },
    ],
    explanation: 'Analyser un flop donne une preuve d’expertise sans promettre de magie.',
    whyItWorks: 'Le viewer apprend sur une erreur réelle et se projette dans son propre contenu.',
    whyNow: 'Les audiences fatiguent des wins parfaits. Les diagnostics honnêtes deviennent plus différenciants.',
    saturationReason: 'Encore early parce que le format demande de montrer un échec concret.',
    recommendedFormats: [
      { label: 'Audit vidéo fictive', duration: '28-38 sec', difficulty: 'medium', why: 'Permet de montrer sans exposer un client.' },
      { label: 'Carrousel diagnostic', duration: '6 slides', difficulty: 'easy', why: 'Chaque erreur devient une décision.' },
    ],
    hooks: [
      'Cette vidéo n’a pas flop à cause de l’algorithme.',
      'Le sujet était bon. Le montage a tué la rétention.',
      'Voici pourquoi cette vidéo aurait dû être une V2, pas un abandon.',
    ],
    angles: ['Auditer les 3 premières secondes.', 'Comparer version flop et version corrigée.', 'Montrer la décision de repost à prendre.'],
    mistakesToAvoid: ['Être humiliant', 'Trop de jargon', 'Ne pas proposer de correction', 'Inventer des métriques'],
    actionPlan: [
      { title: 'Choisir un flop exploitable', description: 'Le sujet doit être bon, seule l’exécution bloque.', effort: 'medium', priority: 'high' },
      { title: 'Nommer la cause exacte', description: 'Hook, preuve, payoff ou CTA.', effort: 'low', priority: 'high' },
      { title: 'Proposer une V2', description: 'La valeur vient de la correction, pas du roast.', effort: 'medium', priority: 'high' },
    ],
  },
  {
    id: 'personne-ne-dit',
    name: 'Ce que personne ne dit sur…',
    category: 'hook_format',
    platform: 'tiktok',
    detectedAt,
    lastUpdatedAt,
    volumeScore: 69,
    velocityScore: 81,
    accelerationScore: 77,
    saturationScore: 57,
    noveltyScore: 52,
    creatorFitScore: 73,
    difficultyScore: 58,
    riskScore: 73,
    recommendedNiches: ['Business', 'Lifestyle', 'Éducation'],
    badFitNiches: ['Food', 'Gaming'],
    timeWindow: { label: 'Fenêtre instable : 24-36h', estimatedHoursLeft: 30 },
    signals: [
      { label: 'Hooks contrarian', value: '+35%', sentiment: 'positive', explanation: 'La tension de non-dit attire encore.' },
      { label: 'Risque clickbait', value: 'élevé', sentiment: 'negative', explanation: 'Les révélations banales détruisent vite la confiance.' },
      { label: 'Commentaires polarisés', value: 'en hausse', sentiment: 'neutral', explanation: 'Le format peut créer du débat utile.' },
    ],
    explanation: 'Le hook attire vite, mais il devient dangereux si la révélation n’est pas précise.',
    whyItWorks: 'La promesse d’un non-dit crée une dette de curiosité.',
    whyNow: 'Le format monte sur les sujets où les créateurs remettent en cause un conseil populaire.',
    saturationReason: 'La structure est proche du clickbait si elle n’apporte pas une observation utile.',
    recommendedFormats: [
      { label: 'Facecam opinion courte', duration: '18-24 sec', difficulty: 'medium', why: 'Le point de vue doit être incarné.' },
      { label: 'Comparaison croyance/réalité', duration: '20 sec', difficulty: 'easy', why: 'Le non-dit devient concret.' },
    ],
    hooks: [
      'Ce que personne ne dit sur les vidéos qui “marchent”.',
      'Le conseil populaire est vrai, mais incomplet.',
      'On parle du hook. On oublie ce qui arrive juste après.',
    ],
    angles: ['Nuancer un conseil populaire.', 'Révéler une conséquence ignorée.', 'Montrer le coût d’un réflexe de créateur.'],
    mistakesToAvoid: ['Faire du clickbait', 'Pas de preuve', 'Ton trop agressif', 'Conclusion floue'],
    actionPlan: [
      { title: 'Choisir une croyance précise', description: 'Pas “TikTok”, mais un réflexe concret.', effort: 'low', priority: 'high' },
      { title: 'Donner une nuance vérifiable', description: 'Le viewer doit repartir avec une décision.', effort: 'medium', priority: 'high' },
      { title: 'Éviter le ton drama', description: 'Premium, direct, pas polémique vide.', effort: 'low', priority: 'medium' },
    ],
  },
  {
    id: 'verite-30-jours',
    name: 'La vérité après 30 jours',
    category: 'creator_growth',
    platform: 'tiktok',
    detectedAt,
    lastUpdatedAt,
    volumeScore: 57,
    velocityScore: 68,
    accelerationScore: 64,
    saturationScore: 42,
    noveltyScore: 70,
    creatorFitScore: 79,
    difficultyScore: 66,
    riskScore: 38,
    recommendedNiches: ['Business', 'Fitness', 'Éducation', 'Lifestyle'],
    badFitNiches: ['Gaming'],
    timeWindow: { label: 'Fenêtre : 72-96h', estimatedHoursLeft: 84 },
    signals: [
      { label: 'Preuve long terme', value: '+21%', sentiment: 'positive', explanation: 'Les audiences valorisent les retours honnêtes.' },
      { label: 'Difficulté production', value: 'haute', sentiment: 'neutral', explanation: 'Le format demande une vraie matière.' },
      { label: 'Saturation', value: 'basse', sentiment: 'positive', explanation: 'Peu de créateurs ont un suivi crédible.' },
    ],
    explanation: 'Le format donne du poids à une conclusion parce qu’elle vient d’une période réelle.',
    whyItWorks: 'La durée rend le retour plus crédible qu’une astuce immédiate.',
    whyNow: 'Le marché fatigue des hacks rapides. Les bilans honnêtes se différencient.',
    saturationReason: 'Encore peu saturé, mais moins urgent car la production est plus longue.',
    recommendedFormats: [
      { label: 'Bilan narratif', duration: '30-45 sec', difficulty: 'hard', why: 'Le temps donne une vraie autorité.' },
      { label: 'Carrousel bilan', duration: '7 slides', difficulty: 'medium', why: 'Les apprentissages deviennent consultables.' },
    ],
    hooks: [
      'Après 30 jours, voilà ce qui a vraiment changé.',
      'Je pensais que le problème était la fréquence. Ce n’était pas ça.',
      'La vérité après 30 jours de posts courts.',
    ],
    angles: ['Bilan d’une routine de contenu.', 'Retour honnête sur une méthode populaire.', 'Ce qui a changé après correction d’un hook.'],
    mistakesToAvoid: ['Bilan sans chiffre', 'Trop long', 'Aucune surprise', 'Conseil trop général'],
    actionPlan: [
      { title: 'Lister 3 apprentissages', description: 'Un apprentissage par partie.', effort: 'medium', priority: 'medium' },
      { title: 'Mettre la surprise en premier', description: 'Ce qui contredit ton attente fait le hook.', effort: 'low', priority: 'high' },
      { title: 'Couper le journal complet', description: 'Le viewer veut la vérité, pas tout le processus.', effort: 'medium', priority: 'medium' },
    ],
  },
  {
    id: 'audio-loop-caption',
    name: 'Audio loop + caption tendue',
    category: 'audio_pattern',
    platform: 'tiktok',
    detectedAt,
    lastUpdatedAt,
    volumeScore: 61,
    velocityScore: 88,
    accelerationScore: 86,
    saturationScore: 61,
    noveltyScore: 58,
    creatorFitScore: 62,
    difficultyScore: 35,
    riskScore: 76,
    recommendedNiches: ['Lifestyle', 'Beauté', 'Food'],
    badFitNiches: ['Business', 'Éducation', 'Coaching'],
    timeWindow: { label: 'Fenêtre instable : 18-30h', estimatedHoursLeft: 26 },
    signals: [
      { label: 'Velocity audio', value: 'très forte', sentiment: 'positive', explanation: 'L’audio circule vite sur des formats visuels.' },
      { label: 'Fit créateur business', value: 'faible', sentiment: 'negative', explanation: 'Le format peut paraître hors positionnement.' },
      { label: 'Risque de copie', value: 'élevé', sentiment: 'negative', explanation: 'Les audios rapides saturent brutalement.' },
    ],
    explanation: 'Le signal monte vite, mais le risque est élevé pour les créateurs expertise.',
    whyItWorks: 'L’audio crée une boucle émotionnelle et la caption ajoute la tension.',
    whyNow: 'La vitesse est forte, mais la fenêtre peut se fermer vite.',
    saturationReason: 'Les audios trend se copient plus vite que les formats éditoriaux.',
    recommendedFormats: [
      { label: 'Caption visuelle courte', duration: '7-12 sec', difficulty: 'easy', why: 'La boucle garde le replay.' },
      { label: 'B-roll + phrase choc', duration: '9 sec', difficulty: 'easy', why: 'Le format sert l’émotion, pas l’explication.' },
    ],
    hooks: [
      'Le détail que tu comprends seulement après avoir posté.',
      'Ce moment où tu réalises que le problème n’était pas le sujet.',
      'La phrase que j’aurais dû écrire avant de publier.',
    ],
    angles: ['Utiliser l’audio pour une confession courte.', 'Transformer une erreur en caption tendue.', 'Faire une boucle sur un avant/après silencieux.'],
    mistakesToAvoid: ['Copier l’audio hors niche', 'Texte trop long', 'Pas de boucle visuelle', 'Publier trop tard'],
    actionPlan: [
      { title: 'Valider le fit niche', description: 'À éviter si ton audience attend un diagnostic expert.', effort: 'low', priority: 'high' },
      { title: 'Écrire une caption courte', description: 'Une phrase, pas un mini script.', effort: 'low', priority: 'medium' },
      { title: 'Poster vite ou passer', description: 'Cette fenêtre est instable.', effort: 'low', priority: 'high' },
    ],
  },
  {
    id: 'hook-confession',
    name: 'Hook confession',
    category: 'hook_format',
    platform: 'tiktok',
    detectedAt,
    lastUpdatedAt,
    volumeScore: 52,
    velocityScore: 83,
    accelerationScore: 79,
    saturationScore: 33,
    noveltyScore: 74,
    creatorFitScore: 86,
    difficultyScore: 34,
    riskScore: 29,
    recommendedNiches: ['Business', 'Coaching', 'Lifestyle', 'Éducation'],
    badFitNiches: ['Gaming'],
    timeWindow: { label: 'Fenêtre courte : 36-48h', estimatedHoursLeft: 40 },
    signals: [
      { label: 'Confessions courtes', value: '+36%', sentiment: 'positive', explanation: 'Les hooks qui assument une erreur personnelle gardent mieux l’attention.' },
      { label: 'Commentaires identification', value: 'en hausse', sentiment: 'positive', explanation: 'Le viewer se reconnaît dans une phrase précise.' },
      { label: 'Risque drama', value: 'faible', sentiment: 'neutral', explanation: 'Le format reste crédible quand la confession mène à une correction.' },
    ],
    explanation: 'Une confession précise crée une tension immédiate sans ressembler à un conseil générique.',
    whyItWorks: 'Le viewer reste parce qu’il veut vérifier si l’erreur racontée est aussi la sienne.',
    whyNow: 'Les créateurs cherchent des hooks plus humains, mais toujours orientés décision.',
    saturationReason: 'Encore peu copié quand la confession reste spécifique et liée à un résultat.',
    recommendedFormats: [
      { label: 'Facecam directe', duration: '16-24 sec', difficulty: 'easy', why: 'La voix rend la confession crédible.' },
      { label: 'Texte écran + cut preuve', duration: '14-20 sec', difficulty: 'medium', why: 'Le texte pose la tension, le cut montre la correction.' },
    ],
    hooks: [
      'J’ai compris trop tard que mon hook expliquait au lieu de retenir.',
      'Je croyais manquer d’idées. En réalité, je cachais l’enjeu.',
      'Cette erreur m’a coûté des posts que j’aurais dû republier.',
    ],
    angles: ['Confesser une erreur de montage.', 'Montrer une mauvaise croyance avant la correction.', 'Transformer une erreur personnelle en règle de repost.'],
    mistakesToAvoid: ['Confession vague', 'Ton trop dramatique', 'Pas de correction', 'Aucune preuve visible'],
    actionPlan: [
      { title: 'Écrire la confession', description: 'Une phrase courte qui avoue une erreur précise.', effort: 'low', priority: 'high' },
      { title: 'Montrer la correction', description: 'Passe de la confession à une décision de montage.', effort: 'medium', priority: 'high' },
      { title: 'Finir par une règle', description: 'Le viewer doit pouvoir appliquer la correction.', effort: 'low', priority: 'medium' },
    ],
  },
  {
    id: 'preuve-rapide',
    name: 'Preuve rapide',
    category: 'visual_format',
    platform: 'tiktok',
    detectedAt,
    lastUpdatedAt,
    volumeScore: 60,
    velocityScore: 87,
    accelerationScore: 84,
    saturationScore: 38,
    noveltyScore: 72,
    creatorFitScore: 91,
    difficultyScore: 46,
    riskScore: 31,
    recommendedNiches: ['Business', 'E-commerce', 'Fitness', 'Beauté', 'Éducation'],
    badFitNiches: [],
    timeWindow: { label: 'Fenêtre courte : 24-48h', estimatedHoursLeft: 32 },
    signals: [
      { label: 'Preuve avant contexte', value: '+42%', sentiment: 'positive', explanation: 'Les vidéos qui montrent le résultat avant l’explication retiennent mieux.' },
      { label: 'Bon potentiel carrousel éducatif', value: 'fort', sentiment: 'positive', explanation: 'Le format se transforme facilement en checklist.' },
      { label: 'Saturation motivation', value: 'moyenne', sentiment: 'neutral', explanation: 'Le risque augmente si la preuve n’est pas visible.' },
    ],
    explanation: 'Le format force le créateur à prouver avant d’expliquer, ce qui réduit la perte d’attention.',
    whyItWorks: 'La preuve donne une raison de rester. Le contexte arrive seulement après.',
    whyNow: 'Les audiences scrollent les promesses abstraites et restent sur les preuves immédiates.',
    saturationReason: 'Le format reste fort si la preuve est concrète et visible dans la première seconde.',
    recommendedFormats: [
      { label: 'Preuve à 0:00', duration: '18-25 sec', difficulty: 'medium', why: 'La première frame fait le travail du hook.' },
      { label: 'Carrousel preuve/règle', duration: '5 slides', difficulty: 'easy', why: 'Le résultat et la règle deviennent sauvegardables.' },
    ],
    hooks: [
      'Regarde la différence avant que je t’explique la méthode.',
      'Le résultat arrive en premier, parce que c’est là que la vidéo se joue.',
      'Tu n’as pas besoin de plus de contexte, tu as besoin de voir ça.',
    ],
    angles: ['Montrer le résultat avant la méthode.', 'Comparer deux intros avec la même idée.', 'Mettre la preuve visuelle avant le storytelling.'],
    mistakesToAvoid: ['Preuve trop tardive', 'Premier plan faible', 'Explication avant résultat', 'Trop de promesse'],
    actionPlan: [
      { title: 'Choisir la preuve la plus lisible', description: 'Elle doit être comprise en une seconde.', effort: 'medium', priority: 'high' },
      { title: 'Couper l’intro', description: 'Tout ce qui précède la preuve doit disparaître.', effort: 'low', priority: 'high' },
      { title: 'Ajouter la règle', description: 'Explique seulement après ce que le viewer vient de voir.', effort: 'low', priority: 'medium' },
    ],
  },
  {
    id: 'repost-ameliore',
    name: 'Repost amélioré',
    category: 'creator_growth',
    platform: 'tiktok',
    detectedAt,
    lastUpdatedAt,
    volumeScore: 48,
    velocityScore: 80,
    accelerationScore: 76,
    saturationScore: 28,
    noveltyScore: 79,
    creatorFitScore: 96,
    difficultyScore: 43,
    riskScore: 22,
    recommendedNiches: ['Business', 'Coaching', 'Éducation', 'Creator growth', 'Lifestyle'],
    badFitNiches: ['Food'],
    timeWindow: { label: 'Fenêtre early : 48-72h', estimatedHoursLeft: 60 },
    signals: [
      { label: 'Reposts pédagogiques', value: '+31%', sentiment: 'positive', explanation: 'Les créateurs montrent de plus en plus la V2, pas seulement le post original.' },
      { label: 'Saturation faible', value: '28/100', sentiment: 'positive', explanation: 'Peu de contenus expliquent encore la décision de repost.' },
      { label: 'Fit Viralynz', value: 'très fort', sentiment: 'positive', explanation: 'Le format colle directement au diagnostic hook → correction → V2.' },
    ],
    explanation: 'Le format montre exactement comment transformer une vidéo moyenne en V2 plus tendue.',
    whyItWorks: 'Le viewer voit une décision concrète : quoi couper, avancer ou réécrire.',
    whyNow: 'Les créateurs veulent recycler mieux au lieu de produire plus au hasard.',
    saturationReason: 'Le format est encore early car il demande un vrai diagnostic, pas seulement une tendance copiée.',
    recommendedFormats: [
      { label: 'Avant/après hook', duration: '22-30 sec', difficulty: 'medium', why: 'La correction est visible et actionnable.' },
      { label: 'Timeline de repost', duration: '6 slides', difficulty: 'easy', why: 'Chaque slide devient une décision de montage.' },
    ],
    hooks: [
      'Cette vidéo ne devait pas être abandonnée. Elle devait être repostée autrement.',
      'Même sujet, meilleur hook : voilà la V2 que j’aurais postée.',
      'Tu n’as pas un problème d’idée, tu as un problème d’angle.',
    ],
    angles: ['Comparer version originale et V2.', 'Montrer quoi couper dans les 3 premières secondes.', 'Transformer un flop en plan de repost.'],
    mistakesToAvoid: ['Changer tout le sujet', 'Ne pas montrer la V1', 'Correction trop abstraite', 'Pas de nouvelle première frame'],
    actionPlan: [
      { title: 'Choisir une vidéo récupérable', description: 'Sujet fort, hook faible, preuve présente.', effort: 'medium', priority: 'high' },
      { title: 'Réécrire les 3 premières secondes', description: 'Le repost doit changer l’ordre, pas seulement les mots.', effort: 'medium', priority: 'high' },
      { title: 'Montrer la V2', description: 'Termine avec la version corrigée prête à poster.', effort: 'medium', priority: 'high' },
    ],
  },
];
